// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type MediaItem struct {
	ID                    int64           `json:"id"`
	LibrarySectionID      sql.NullInt64   `json:"library_section_id"`
	SectionLocationID     sql.NullInt64   `json:"section_location_id"`
	MetadataItemID        sql.NullInt64   `json:"metadata_item_id"`
	TypeID                sql.NullInt64   `json:"type_id"`
	Width                 sql.NullInt64   `json:"width"`
	Height                sql.NullInt64   `json:"height"`
	Size                  interface{}     `json:"size"`
	Duration              sql.NullInt64   `json:"duration"`
	Bitrate               sql.NullInt64   `json:"bitrate"`
	Container             sql.NullString  `json:"container"`
	VideoCodec            sql.NullString  `json:"video_codec"`
	AudioCodec            sql.NullString  `json:"audio_codec"`
	DisplayAspectRatio    sql.NullFloat64 `json:"display_aspect_ratio"`
	FramesPerSecond       sql.NullFloat64 `json:"frames_per_second"`
	AudioChannels         sql.NullInt64   `json:"audio_channels"`
	Interlaced            sql.NullBool    `json:"interlaced"`
	Source                sql.NullString  `json:"source"`
	Hints                 sql.NullString  `json:"hints"`
	DisplayOffset         sql.NullInt64   `json:"display_offset"`
	Settings              sql.NullString  `json:"settings"`
	CreatedAt             interface{}     `json:"created_at"`
	UpdatedAt             interface{}     `json:"updated_at"`
	OptimizedForStreaming sql.NullBool    `json:"optimized_for_streaming"`
	DeletedAt             interface{}     `json:"deleted_at"`
	MediaAnalysisVersion  sql.NullInt64   `json:"media_analysis_version"`
	SampleAspectRatio     sql.NullFloat64 `json:"sample_aspect_ratio"`
	ExtraData             sql.NullString  `json:"extra_data"`
	ProxyType             sql.NullInt64   `json:"proxy_type"`
	ChannelID             sql.NullInt64   `json:"'channel_id'"`
	BeginsAt              interface{}     `json:"'begins_at'"`
	EndsAt                interface{}     `json:"'ends_at'"`
	ColorTrc              sql.NullString  `json:"'color_trc'"`
}

type MediaPart struct {
	ID               int64          `json:"id"`
	MediaItemID      sql.NullInt64  `json:"media_item_id"`
	DirectoryID      sql.NullInt64  `json:"directory_id"`
	Hash             sql.NullString `json:"hash"`
	OpenSubtitleHash sql.NullString `json:"open_subtitle_hash"`
	File             sql.NullString `json:"file"`
	Index            sql.NullInt64  `json:"index"`
	Size             interface{}    `json:"size"`
	Duration         sql.NullInt64  `json:"duration"`
	CreatedAt        interface{}    `json:"created_at"`
	UpdatedAt        interface{}    `json:"updated_at"`
	DeletedAt        interface{}    `json:"deleted_at"`
	ExtraData        sql.NullString `json:"extra_data"`
}

type Tag struct {
	ID             int64          `json:"id"`
	MetadataItemID sql.NullInt64  `json:"metadata_item_id"`
	Tag            sql.NullString `json:"tag"`
	TagType        sql.NullInt64  `json:"tag_type"`
	UserThumbUrl   sql.NullString `json:"user_thumb_url"`
	UserArtUrl     sql.NullString `json:"user_art_url"`
	UserMusicUrl   sql.NullString `json:"user_music_url"`
	CreatedAt      interface{}    `json:"created_at"`
	UpdatedAt      interface{}    `json:"updated_at"`
	TagValue       sql.NullInt64  `json:"tag_value"`
	ExtraData      sql.NullString `json:"extra_data"`
	Key            sql.NullString `json:"'key'"`
	ParentID       sql.NullInt64  `json:"'parent_id'"`
}

type Tagging struct {
	ID             int64          `json:"id"`
	MetadataItemID sql.NullInt64  `json:"metadata_item_id"`
	TagID          sql.NullInt64  `json:"tag_id"`
	Index          sql.NullInt64  `json:"index"`
	Text           sql.NullString `json:"text"`
	TimeOffset     sql.NullInt64  `json:"time_offset"`
	EndTimeOffset  sql.NullInt64  `json:"end_time_offset"`
	ThumbUrl       sql.NullString `json:"thumb_url"`
	CreatedAt      interface{}    `json:"created_at"`
	ExtraData      sql.NullString `json:"extra_data"`
}
