// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetMediaByTag(ctx context.Context, tag sql.NullString) ([]sql.NullString, error)
}

var _ Querier = (*Queries)(nil)
