// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const getMediaByTag = `-- name: GetMediaByTag :many
SELECT
  mp.file
FROM media_parts mp
  INNER JOIN media_items mi ON mp.media_item_id = mi.id
  INNER JOIN taggings tg ON mi.metadata_item_id = tg.metadata_item_id
  INNER JOIN tags t ON tg.tag_id = t.id
WHERE
  t.tag_type = 314 AND t.tag = ?
`

func (q *Queries) GetMediaByTag(ctx context.Context, tag sql.NullString) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getMediaByTag, tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var file sql.NullString
		if err := rows.Scan(&file); err != nil {
			return nil, err
		}
		items = append(items, file)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
